In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import math

In [2]:
def normpdf(x, mean, var):
    denom = (2*math.pi*var)**.5
    num = math.exp(-(float(x)-float(mean))**2/(2*var))
    return num/denom
def getmaxindex(array):
    max_index=0
    for i in range(array.size):
        if(array[max_index]<array[i]):
            max_index = i        
    return max_index
def getclass(test,mean,var):
    probaility = np.zeros(10)
    for i in range(10):
        muse = mean[i]
        variance = var[i]
        prob = np.zeros(784)
        for j in range(muse.size):
            prob[j] = (normpdf(test[j], muse[j], variance[j]))
        probaility[i] = np.prod(prob)
    return getmaxindex(probaility)

In [3]:
#-----------------Create X----------------------
x = np.zeros((2400,784))
for i in range(x.shape[0]):
    image_index = str(i+1)
    url = "./Train/"+image_index+".jpg"
    image = plt.imread(url)
    x[i] = np.divide(np.array(image.flatten()), 255)
#-----------------Create T----------------------
t = np.zeros((2400,10))
for z in range(t.shape[1]):
    rangez = (z+1)*240
    for y in range(t.shape[0]):
        if(y>=rangez-240 and y<rangez):
            t[y][z]=1
        else:
            t[y][z]=-1
#--------------------Create X_Test-------------------------------
x_test = np.zeros((200,784))
for i in range(x_test.shape[0]):
    image_index = str(i+1)
    url = "./Test/"+image_index+".jpg"
    image = plt.imread(url)
    x_test[i] = np.divide(np.array(image.flatten()), 255)

In [5]:
classes = np.split(x,10)
mean = np.zeros((10,784))
var = np.zeros((10,784))
for i in range(10):
    mean[i] = np.mean(classes[i],0)
    var[i] = np.var(classes[i],0)
var = np.where(var<0.01,0.01,var)
confusion_matrix =np.full((10,10),0)
for i in range(x_test.shape[0]):
    max = getclass(x_test[i],mean,var)
    confusion_matrix[int(i/20)][max] = confusion_matrix[int(i/20)][max]+1
print(confusion_matrix)

[[18  0  0  0  0  0  1  0  1  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 16  0  0  1  1  0  1  1]
 [ 0  0  0 17  0  1  0  0  2  0]
 [ 0  0  0  0 12  0  3  0  1  4]
 [ 0  0  0  0  2 14  0  0  3  1]
 [ 0  0  0  0  0  0 19  0  1  0]
 [ 0  0  0  0  3  0  0 12  0  5]
 [ 1  0  0  0  0  0  0  0 18  1]
 [ 1  0  0  1  3  0  0  1  1 13]]
