In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
#-----------------Create X----------------------
x = np.zeros((2400,785))
for i in range(x.shape[0]):
    image_index = str(i+1)
    url = "./Train/"+image_index+".jpg"
    image = plt.imread(url)
    x[i] = np.append(image.flatten(),[1])
#-----------------Create T----------------------
t = np.zeros((2400,10))
for z in range(t.shape[1]):
    rangez = (z+1)*240
    for y in range(t.shape[0]):
        if(y>=rangez-240 and y<rangez):
            t[y][z]=1
        else:
            t[y][z]=-1
t = np.transpose(t)
#--------------------Create X_Test-------------------------------
x_test = np.zeros((200,785))
for i in range(x_test.shape[0]):
    image_index = str(i+1)
    url = "./Test/"+image_index+".jpg"
    image = plt.imread(url)
    x_test[i] = np.append(image.flatten(),[1])

In [3]:
#--------------Perceptron-----------#
def perceptron(x,t,n):
    w = np.zeros((10,785))
    for i in range(w.shape[0]):
        w_initial = w[i]
        w_initial[0] = 1
        target = t[i]
        for j in range(500):
            for k in range(x.shape[0]):
                cx = x[k]
                p = np.dot(cx,np.transpose(w_initial))
                if p>=0:
                    p = 1
                if p<0:
                    p=-1
                if(p!=target[k]):
                    step = target[k]*n
                    w_initial = w_initial + (cx*step)
        w[i]= w_initial;
    return w

In [4]:
def getmaxindex(array):
    max_index=0
    for i in range(array.size):
        if(array[max_index]<array[i]):
            max_index = i        
    return max_index
def confusion(x_test,x,t,n):
    w = perceptron(x,t,n)
    y = np.dot(x_test, np.transpose(w))
    final_sol = np.full((200,1),-1)
    for i in range(y.shape[0]):
        final_sol[i][0] = getmaxindex(y[i])
    confusion_matrix =np.full((10,10),0)
    for i in range(final_sol.shape[0]):
        confusion_matrix[int(i/20)][final_sol[i][0]] = confusion_matrix[int(i/20)][final_sol[i][0]]+1
    print(confusion_matrix)

In [5]:
confusion(x_test,x,t,1)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 15  0  0  0  0  2  2]
 [ 0  0  0  0 17  1  0  0  0  2]
 [ 0  0  1  0  2 16  0  0  1  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 15  0  5]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [6]:
confusion(x_test,x,t,0.1)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 15  0  0  0  0  2  2]
 [ 0  0  0  0 17  1  0  0  0  2]
 [ 0  0  1  0  2 16  0  0  1  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 15  0  5]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [7]:
confusion(x_test,x,t,0.01)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 15  0  0  0  0  2  2]
 [ 0  0  0  0 17  1  0  0  0  2]
 [ 0  0  1  0  2 16  0  0  1  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 15  0  5]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [8]:
confusion(x_test,x,t,0.001)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 13  0  1  0  0  3  2]
 [ 0  0  0  0 17  0  0  0  0  3]
 [ 0  0  1  0  2 15  0  0  2  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 15  0  5]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [9]:
confusion(x_test,x,t,0.0001)

[[20  0  0  0  0  0  0  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  0  1  1  0  0  1  0]
 [ 0  0  1 14  0  1  0  0  3  1]
 [ 0  0  0  0 16  2  0  0  1  1]
 [ 0  0  0  0  1 17  0  0  2  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 14  0  6]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [10]:
confusion(x_test,x,t,0.00001)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 1  0  1 14  0  0  0  0  1  3]
 [ 0  1  0  0 16  0  0  0  0  3]
 [ 0  0  1  0  2 14  0  0  3  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 12  0  8]
 [ 0  0  0  0  0  0  0  0 18  2]
 [ 1  0  0  0  0  0  0  2  1 16]]


In [11]:
confusion(x_test,x,t,0.000001)

[[19  0  0  0  0  0  1  0  0  0]
 [ 0 18  1  0  0  0  0  0  1  0]
 [ 0  1 16  1  1  0  0  0  1  0]
 [ 0  0  1 15  0  1  0  0  1  2]
 [ 0  1  0  0 16  0  0  0  0  3]
 [ 0  0  1  0  2 16  0  0  1  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 15  0  5]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 0  0  1  0  0  0  0  2  2 15]]


In [12]:
confusion(x_test,x,t,0.0000001)

[[18  0  0  0  0  0  1  1  0  0]
 [ 0 19  0  0  0  0  0  0  1  0]
 [ 0  0 16  1  1  0  1  0  1  0]
 [ 0  0  1 16  0  0  0  0  2  1]
 [ 0  0  0  0 14  2  0  0  1  3]
 [ 0  0  1  1  0 16  0  0  2  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  0  0  0 16  0  4]
 [ 0  0  0  0  0  0  0  0 18  2]
 [ 0  0  1  0  0  0  0  2  1 16]]


In [13]:
confusion(x_test,x,t,0.00000001)

[[19  0  0  0  0  0  0  1  0  0]
 [ 0 19  0  0  0  0  0  0  1  0]
 [ 0  0 16  1  1  0  1  0  1  0]
 [ 0  0  1 17  0  0  0  0  2  0]
 [ 0  0  0  0 16  1  0  0  0  3]
 [ 0  0  1  1  0 17  0  0  1  0]
 [ 0  0  0  0  0  1 18  0  1  0]
 [ 0  0  0  0  1  0  0 17  0  2]
 [ 0  0  0  0  0  0  0  0 19  1]
 [ 0  0  1  0  0  0  0  3  1 15]]


In [14]:
confusion(x_test,x,t,0.000000001)

[[20  0  0  0  0  0  0  0  0  0]
 [ 0 19  0  0  0  0  0  0  1  0]
 [ 0  0 16  0  1  1  1  0  1  0]
 [ 0  0  1 17  0  1  0  0  1  0]
 [ 0  0  0  0 16  1  0  0  0  3]
 [ 0  0  1  1  0 17  0  0  1  0]
 [ 0  0  1  0  0  0 18  0  1  0]
 [ 0  0  0  0  2  0  0 18  0  0]
 [ 0  0  0  1  0  0  0  0 19  0]
 [ 0  0  1  0  0  1  0  4  0 14]]
